# Generated by Django 5.1.3 on 2025-12-03 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('groupId', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('contactName', models.CharField(blank=True, max_length=100, null=True)),
                ('contactPhone', models.CharField(blank=True, max_length=50, null=True)),
                ('hourlyRate', models.FloatField()),
                ('coordinates', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('adminId', models.CharField(max_length=64)),
                ('admins', models.JSONField(blank=True, default=list)),
                ('name', models.CharField(max_length=200)),
                ('sport', models.CharField(max_length=100)),
                ('inviteCode', models.CharField(max_length=50)),
                ('createdAt', models.CharField(max_length=50)),
                ('members', models.JSONField(blank=True, default=list)),
                ('pendingRequests', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('groupId', models.CharField(max_length=64)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=10)),
                ('fieldId', models.CharField(max_length=64)),
                ('confirmedPlayerIds', models.JSONField(blank=True, default=list)),
                ('paidPlayerIds', models.JSONField(blank=True, default=list)),
                ('teamA', models.JSONField(blank=True, default=list)),
                ('teamB', models.JSONField(blank=True, default=list)),
                ('scoreA', models.IntegerField()),
                ('scoreB', models.IntegerField()),
                ('finished', models.BooleanField(default=False)),
                ('mvpId', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('groupId', models.CharField(max_length=64)),
                ('userId', models.CharField(blank=True, max_length=64, null=True)),
                ('name', models.CharField(max_length=200)),
                ('nickname', models.CharField(max_length=200)),
                ('birthDate', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('favoriteTeam', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('matchesPlayed', models.IntegerField()),
                ('avatar', models.TextField(blank=True, null=True)),
                ('isMonthlySubscriber', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('groupId', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('type', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('relatedPlayerId', models.CharField(blank=True, max_length=64, null=True)),
                ('relatedMatchId', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
