# Generated by Django 5.1.3 on 2025-12-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='logo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
