# Generated by Django 5.1.3 on 2025-12-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_group_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='isGuest',
            field=models.BooleanField(default=False),
        ),
    ]
