# Generated by Django 5.1.3 on 2025-12-05 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_player_phone_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='fixedAmount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='paymentMode',
            field=models.CharField(default='fixed', max_length=20),
        ),
    ]
