# Generated by Django 5.1.3 on 2025-12-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_group_fixedamount_group_paymentmode'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='monthlyStartMonth',
            field=models.CharField(max_length=7, null=True, blank=True),
        ),
    ]
