# Generated by Django 5.1.3 on 2025-12-05 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_group_fixedamount_group_paymentmode'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='city',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
