# Generated by Django 5.1.3 on 2025-12-09 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_group_monthlyfee'),
        ('core', '0007_merge_0006'),
    ]

    operations = [
    ]
